services:
  haniflix_backend:
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      IS_IN_DOCKER: is_docker
    container_name: haniflix_backend
    working_dir: /usr/app
    volumes:
      - ./:/usr/app
      - /var/www/html/cdn.haniflix.com/movies:/usr/movies
      - /var/www/html/uploads:/usr/app/uploads
      - /var/www/html/logs:/usr/app/logs
      - /usr/app/node_modules
    ports:
      - 8800:8800
    restart: unless-stopped
